version: '3.8'

services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=quiz_db
      - POSTGRES_USER=quiz_user
      - POSTGRES_PASSWORD=quiz_password

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=quiz_db
      - DB_USER=quiz_user
      - DB_PASSWORD=quiz_password
    depends_on:
      - db

volumes:
  postgres_data: